import { Platform } from "react-native";
import { MD3LightTheme as DefaultTheme } from "react-native-paper";

const fontMap = {
  ios: {
    Syne_400Regular: "Syne-Regular",
    Syne_500Medium: "Syne-Medium",
    Syne_600SemiBold: "Syne-SemiBold",
    Syne_700Bold: "Syne-Bold",
    Syne_800ExtraBold: "Syne-ExtraBold",
  },
  android: {
    Syne_400Regular: "Syne_400Regular",
    Syne_500Medium: "Syne_500Medium",
    Syne_600SemiBold: "Syne_600SemiBold",
    Syne_700Bold: "Syne_700Bold",
    Syne_800ExtraBold: "Syne_800ExtraBold",
  },
};
const fonts = fontMap[Platform.OS as keyof typeof fontMap];

export const lightTheme: typeof DefaultTheme = {
  ...DefaultTheme,
  animation: {
    scale: 1.0,
    defaultAnimationDuration: 200,
  },
  mode: "adaptive",
  dark: false,
  roundness: 4,
  isV3: true,
  version: 3,
  fonts: {
    displayLarge: {
      fontFamily: fonts.Syne_800ExtraBold,
      fontSize: 24,
      fontWeight: "800",
      letterSpacing: 0,
      lineHeight: 32,
    },
    displayMedium: {
      fontFamily: fonts.Syne_700Bold,
      fontSize: 20,
      fontWeight: "700",
      letterSpacing: 0,
      lineHeight: 28,
    },
    displaySmall: {
      fontFamily: fonts.Syne_600SemiBold,
      fontSize: 16,
      fontWeight: "600",
      letterSpacing: 0,
      lineHeight: 24,
    },
    headlineLarge: {
      fontFamily: fonts.Syne_700Bold,
      fontSize: 22,
      fontWeight: "700",
      letterSpacing: 0.15,
      lineHeight: 28,
    },
    headlineMedium: {
      fontFamily: fonts.Syne_600SemiBold,
      fontSize: 20,
      fontWeight: "600",
      letterSpacing: 0.15,
      lineHeight: 26,
    },
    headlineSmall: {
      fontFamily: fonts.Syne_600SemiBold,
      fontSize: 18,
      fontWeight: "600",
      letterSpacing: 0.1,
      lineHeight: 24,
    },
    titleLarge: {
      fontFamily: fonts.Syne_700Bold,
      fontSize: 20,
      fontWeight: "700",
      letterSpacing: 0.15,
      lineHeight: 28,
    },
    titleMedium: {
      fontFamily: fonts.Syne_600SemiBold,
      fontSize: 16,
      fontWeight: "600",
      letterSpacing: 0.15,
      lineHeight: 24,
    },
    titleSmall: {
      fontFamily: fonts.Syne_600SemiBold,
      fontSize: 14,
      fontWeight: "600",
      letterSpacing: 0.1,
      lineHeight: 20,
    },
    bodyLarge: {
      fontFamily: fonts.Syne_400Regular,
      fontSize: 16,
      fontWeight: "400",
      letterSpacing: 0.5,
      lineHeight: 24,
    },
    bodyMedium: {
      fontFamily: fonts.Syne_400Regular,
      fontSize: 14,
      fontWeight: "400",
      letterSpacing: 0.25,
      lineHeight: 20,
    },
    bodySmall: {
      fontFamily: fonts.Syne_400Regular,
      fontSize: 12,
      fontWeight: "400",
      letterSpacing: 0.4,
      lineHeight: 16,
    },
    labelLarge: {
      fontFamily: fonts.Syne_500Medium,
      fontSize: 16,
      fontWeight: "500",
      letterSpacing: 0.1,
      lineHeight: 20,
    },
    labelMedium: {
      fontFamily: fonts.Syne_500Medium,
      fontSize: 14,
      fontWeight: "500",
      letterSpacing: 0.5,
      lineHeight: 16,
    },
    labelSmall: {
      fontFamily: fonts.Syne_500Medium,
      fontSize: 12,
      fontWeight: "500",
      letterSpacing: 0.5,
      lineHeight: 16,
    },
    default: {
      fontFamily: fonts.Syne_400Regular,
      fontWeight: "400",
      letterSpacing: 0.5,
    },
  },
  colors: {
    primary: "#6200ee",
    onPrimary: "#ffffff",
    primaryContainer: "#bb86fc",
    onPrimaryContainer: "#000000",
    secondary: "#03dac6",
    onSecondary: "#000000",
    secondaryContainer: "#018786",
    onSecondaryContainer: "#ffffff",
    tertiary: "#03dac6",
    onTertiary: "#000000",
    tertiaryContainer: "#018786",
    onTertiaryContainer: "#ffffff",
    error: "#b00020",
    onError: "#ffffff",
    errorContainer: "#cf6679",
    onErrorContainer: "#000000",
    background: "#f6f6f6",
    onBackground: "#000000",
    surface: "#ffffff",
    onSurface: "#000000",
    surfaceVariant: "#e7e0ec",
    onSurfaceVariant: "#49454f",
    outline: "#79747e",
    outlineVariant: "#c4c3c7",
    shadow: "#000000",
    scrim: "#000000",
    inverseSurface: "#313033",
    inverseOnSurface: "#f4eff4",
    inversePrimary: "#d0bcff",
    elevation: {
      level0: "transparent",
      level1: "#f6f6f6",
      level2: "#ededed",
      level3: "#e4e2e6",
      level4: "#e2e0e5",
      level5: "#e0dee3",
    },
    surfaceDisabled: "rgba(0, 0, 0, 0.12)",
    onSurfaceDisabled: "rgba(0, 0, 0, 0.38)",
    backdrop: "rgba(0, 0, 0, 0.4)",
  },
};

export const darkTheme: typeof DefaultTheme = {
  ...DefaultTheme,
  animation: {
    scale: 1.0,
    defaultAnimationDuration: 200,
  },
  mode: "adaptive",
  dark: true,
  roundness: 4,
  isV3: true,
  version: 3,
  fonts: lightTheme.fonts,
  colors: {
    primary: "#bb86fc",
    onPrimary: "#000000",
    primaryContainer: "#6200ee",
    onPrimaryContainer: "#ffffff",
    secondary: "#03dac6",
    onSecondary: "#000000",
    secondaryContainer: "#03dac6",
    onSecondaryContainer: "#000000",
    tertiary: "#03dac6",
    onTertiary: "#000000",
    tertiaryContainer: "#03dac6",
    onTertiaryContainer: "#000000",
    error: "#cf6679",
    onError: "#000000",
    errorContainer: "#b00020",
    onErrorContainer: "#ffffff",
    background: "#121212",
    onBackground: "#ffffff",
    surface: "#1e1e1e",
    onSurface: "#ffffff",
    surfaceVariant: "#49454f",
    onSurfaceVariant: "#e7e0ec",
    outline: "#c4c3c7",
    outlineVariant: "#79747e",
    shadow: "#000000",
    scrim: "#000000",
    inverseSurface: "#f4eff4",
    inverseOnSurface: "#313033",
    inversePrimary: "#6200ee",
    elevation: {
      level0: "transparent",
      level1: "#1e1e1e",
      level2: "#232323",
      level3: "#282828",
      level4: "#2c2c2c",
      level5: "#303030",
    },
    surfaceDisabled: "rgba(255, 255, 255, 0.12)",
    onSurfaceDisabled: "rgba(255, 255, 255, 0.38)",
    backdrop: "rgba(0, 0, 0, 0.4)",
  },
};
